package edu.virginia.cs.tspim.gui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JDialog;
import javax.swing.JLabel;

import org.opencv.core.Core;

import edu.virginia.cs.tspim.DensitySampler;
import edu.virginia.cs.tspim.GrayScaleConverter;
import edu.virginia.cs.tspim.util.Config;
import edu.virginia.cs.tspim.util.Util;

/**
 *
 * @author saikat
 */
public class MainGui extends javax.swing.JFrame {
    private String filePath;
    private FileOpener fp;

    /**
     * Creates new form MainGui
     */
    public MainGui() {
        this.filePath = "";
        initComponents();
    }
    
    public void setFilePath(String p){
        this.filePath = p;
        filePathTextBox.setText(p);
        if(fp != null){
            fp.setVisible(false);
        }
//        System.out.println();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	openButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        filePathTextBox = new javax.swing.JTextPane();
        runAlgorithmButton = new javax.swing.JButton();
        alphaChooser = new javax.swing.JSlider();
        alphaDefaultLabel1 = new javax.swing.JLabel();
        blockSizeChooser = new javax.swing.JSpinner();
        blockSizeDefaultLabel = new javax.swing.JLabel();
        alphaValurLbl = new javax.swing.JLabel();
        scaleSlider = new javax.swing.JSlider();
        scaleDefaultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        openButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        openButton.setText("Open");
        openButton.setActionCommand("Open");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(filePathTextBox);

        runAlgorithmButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        runAlgorithmButton.setText("Run");
        runAlgorithmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runAlgorithmButtonActionPerformed(evt);
            }
        });

        alphaChooser.setMinorTickSpacing(10);
        alphaChooser.setPaintTicks(true);
        alphaChooser.setValue(75);
        alphaChooser.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                alphaChooserStateChanged(evt);
            }
        });

        alphaDefaultLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        alphaDefaultLabel1.setText("Alpha");

        blockSizeChooser.setRequestFocusEnabled(false);
        blockSizeChooser.setValue(1);
        blockSizeChooser.setVerifyInputWhenFocusTarget(false);

        blockSizeDefaultLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        blockSizeDefaultLabel.setText("Block Size");

        alphaValurLbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        alphaValurLbl.setText("0.75");

        scaleSlider.setMajorTickSpacing(1);
        scaleSlider.setMaximum(10);
        scaleSlider.setMinimum(1);
        scaleSlider.setMinorTickSpacing(1);
        scaleSlider.setPaintLabels(true);
        scaleSlider.setPaintTicks(true);
        scaleSlider.setValue(2);

        scaleDefaultLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        scaleDefaultLabel.setText("Scale");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(runAlgorithmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(scaleSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addComponent(alphaChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(blockSizeChooser, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blockSizeDefaultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(alphaValurLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alphaDefaultLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(openButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scaleDefaultLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(openButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(alphaValurLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alphaChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alphaDefaultLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scaleSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(scaleDefaultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blockSizeChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockSizeDefaultLabel))
                .addGap(18, 18, 18)
                .addComponent(runAlgorithmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        fp = new FileOpener(this);
        fp.setVisible(true);
    }                                          

    private void runAlgorithmButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        int d = alphaChooser.getValue();
        double alpha = d / 100.00;
        int scale = scaleSlider.getValue();
        int blockSize = (int)blockSizeChooser.getValue();
        if(filePath.endsWith(".jpg") || filePath.endsWith(".JPG") || 
                filePath.endsWith(".png") || filePath.endsWith(".PNG") ||
                filePath.endsWith(".bmp") || filePath.endsWith(".BMP") ||
                filePath.endsWith(".jpeg") || filePath.endsWith(".JPEG")){
            //System.out.println(filePath + " " + alpha + " " + blockSize );
        	Config.getInstance().setAlpha(alpha);
        	Config.getInstance().setFileName(filePath);
        	Config.getInstance().setBlockSize(blockSize);
        	Config.getInstance().setScale(scale);
        	
        	Util.logln(Config.getInstance());
        	//this.setVisible(false);
        	Thread t = new Thread(new Runnable() {
				@Override
				public void run() {
					System.loadLibrary( Core.NATIVE_LIBRARY_NAME);
		        	String file_name = Config.getInstance().getFileName();//input_sc.nextLine();
		            GrayScaleConverter con = new GrayScaleConverter(file_name);
		            con.convertToGray();
		            DensitySampler s = new DensitySampler(con.get_array(),con.getThreshold());
		            s.genSample();
				}
			});
        	t.start();
        	try {
				t.join();
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
        	
        }
        else if(filePath == ""){
            JDialog dialog = new JDialog(this);
            dialog.setSize(300, 100);
            JLabel lb = new JLabel();
            lb.setText("Please select a file first");
            dialog.add(lb);
            dialog.setVisible(true);
        }
        else{
            JDialog dialog = new JDialog(this);
            dialog.setSize(300, 100);
            JLabel lb = new JLabel();
            lb.setText("Only JPG PNG BMP\n files are supported");
            dialog.add(lb);
            dialog.setVisible(true);
        }
    }                                                  

    private void alphaChooserStateChanged(javax.swing.event.ChangeEvent evt) {                                          
         int v = alphaChooser.getValue();
         double d = v / 100.0;
         alphaValurLbl.setText(String.format("%.2f", d));
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
                new MainGui().setVisible(true);
//            }
//        });
    }

 // Variables declaration - do not modify                     
    private javax.swing.JSlider alphaChooser;
    private javax.swing.JLabel alphaValurLbl;
    private javax.swing.JSpinner blockSizeChooser;
    private javax.swing.JTextPane filePathTextBox;
    private javax.swing.JLabel alphaDefaultLabel1;
    private javax.swing.JLabel blockSizeDefaultLabel;
    private javax.swing.JLabel scaleDefaultLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider scaleSlider;
    private javax.swing.JButton openButton;
    private javax.swing.JButton runAlgorithmButton;
    // End of variables declaration                     
}
