package edu.virginia.cs.tspim;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;

import edu.virginia.cs.tspim.gui.MainGui;
import edu.virginia.cs.tspim.util.Config;
import edu.virginia.cs.tspim.util.Util;

public class Image extends JFrame{
	
	class ImageViewer extends JFrame{
		private String title;
		private BufferedImage img = null;
		
		public ImageViewer(String title) {
			super(title);
			this.title = title;
		}
		
		/**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private ImageViewer initComponents(BufferedImage iconImg) {
	    	this.img = iconImg;
	        jScrollPane1 = new javax.swing.JScrollPane();
	        imageLabel = new javax.swing.JLabel();
	        saveButton = new javax.swing.JButton();
	        closeButton = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

	        imageLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
	        imageLabel.setToolTipText("");
	        imageLabel.setName(""); // NOI18N
	        imageLabel.setIcon(new ImageIcon(iconImg));
	        imageLabel.setPreferredSize(new java.awt.Dimension(width, height));
	        jScrollPane1.setViewportView(imageLabel);

	        saveButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
	        saveButton.setText("Save");
	        saveButton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                saveButtonActionPerformed(evt);
	            }
	        });

	        closeButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
	        closeButton.setText("Close");
	        closeButton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                closeButtonActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                    .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
	        );

	        pack();
	        setTitle(title);
	        return this;
	    }// </editor-fold>                        

	    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {       
	        this.dispose();
	    }                                           

	    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
	        JFileChooser ch = new JFileChooser();
	        ch.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
	        int r = ch.showOpenDialog(this);
	        if(r == JFileChooser.APPROVE_OPTION){
	            File fp = ch.getSelectedFile();
	            if(fp.isDirectory()){
	                fp = new File(fp, this.title + ".jpg");
	            }
	            try {
					Image.this.writeImageToDisk(fp.getAbsolutePath());
				} catch (IOException e1) {
					e1.printStackTrace();
				}
	            dispose();
	        } 
	    }
	    
	 // Variables declaration - do not modify                     
	    private javax.swing.JButton closeButton;
	    private javax.swing.JLabel imageLabel;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JButton saveButton;
	    // End of variables declaration
	}
	int [][] nodes;
	int width;
	int height;
	int scale;
	private String title;
	private BufferedImage originalImage;
	
	public Image(int width, int height, int scale, String title){
		this.scale = scale;
		this.title = title;
		try {
			originalImage = ImageIO.read(new File(Config.getInstance().getFileName()));
		} catch (IOException e) {
			e.printStackTrace();
		}
		nodes = new int[height * scale][width *scale];
		this.width = scale * width;
		this.height = scale * height;
		for(int i = 0; i < this.height; i++){
			for(int j = 0; j < this.width; j++){
				nodes[i][j] = 0xffffffff; //Initialize all pixel as White
			}
		}
	}
	
	public void setNodeInImage(Node n){
		nodes[n.getX()][n.getY()] = 0;
	}
	
	public void setColoredNodeInImage(Node n, int color){
		nodes[n.getX()][n.getY()] = color;
	}
	
	public void setScaledNodeInImage(Node n){
		nodes[scale * n.getX()] [scale * n.getY()] = 0;
	}
	
	private int getAppropriateColot(int c1, int c2, int steps, int i){
		int a1 = (int)(c1 & 0xff);
		int r1 = (int)((c1 >> 4) & 0xff);
		int g1 = (int)((c1 >> 8) & 0xff);
		int b1 = (int)((c1 >> 12) & 0xff);
		
		int a2 = (int)(c2 & 0xff);
		int r2 = (int)((c2 >> 4) & 0xff);
		int g2 = (int)((c2 >> 8) & 0xff);
		int b2 = (int)((c2 >> 12) & 0xff);
		
		double da = (a1 - a2) / (double)steps;
		double dr = (r1 - r2) / (double)steps;
		double dg = (g1 - g2) / (double)steps;
		double db = (b1 - b2) / (double)steps;
		
		int a = (int) Math.round(a1 + da * i);
		int r = (int) Math.round(r1 + dr * i);
		int g = (int) Math.round(g1 + dg * i);
		int b = (int) Math.round(b1 + db * i);
		int c = (b << 12) | (g << 8) | (r << 4) | (a);
		return c;
	}
	
	public void drawLine(Node a1, Node b1){
		int c1 = originalImage.getRGB(a1.getY(), a1.getX());
		int c2 = originalImage.getRGB(b1.getY(), b1.getX());
		
//		Util.logln(a);
//		Util.logln(b);
		Node a = new Node(scale * a1.getX(), scale * a1.getY());
		Node b = new Node(scale * b1.getX(), scale * b1.getY());
		int dx = b.getX() - a.getX();
		int dy = b.getY() - a.getY();
		int steps = 0;
		if(Math.abs(dx) > Math.abs(dy)){
			steps = Math.abs(dx);
		}
		else{
			steps = Math.abs(dy);
		}
		double xImcr = (double)dx / steps;
		double yIncr = (double)dy / steps;
		double x = a.getX();
		double y = a.getY();
		for(int i = 0; i < steps; i++){
			Node point = new Node((int)Math.round(x), (int)Math.round(y));
			//setNodeInImage(point);
			int c = getAppropriateColot(c1, c2, steps, i);
			setColoredNodeInImage(point, c);
			x += xImcr;
			y += yIncr;
		}
	}
	
	public BufferedImage extractImage(){
		BufferedImage img = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
		for(int i = 0; i < height; i++){
			for(int j = 0; j < width; j++){
				img.setRGB(j, i, nodes[i][j]);
			}
		}
		return img;
	}
	
	public void writeImageToDisk(String path) throws IOException{
		File file = new File(path);
		ImageIO.write(extractImage(), "jpg", file);
	}
	

	public void showImage(){
		this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		BufferedImage iconImage = extractImage();
		new Thread(new Runnable() {
			@Override
			public void run() {
				new ImageViewer(title).initComponents(iconImage).setVisible(true);;
			}
		}).start();;
        
	}
}
